### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Ruth Robertson",
  "email": "rtuh@example.com",
  "password": "password",
  "password_confirmation": "password"
}
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Anna",
  "email": "anna@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "anna@example.com",
  "password": "password"
}
@jwt_anna = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc5NDg2MDZ9.cLHQCVifGVtIPAeOoru9nuOi3s2nijbX4JtsL22qT-w